### PR TITLE
Adding deprecation package. Modification of the baseline.

### PR DESCRIPTION
**Pull request by sbragagnolo**
We added a new Package for deprecated classes. 
Added also the package to the baseline with the pertinent dependancies

### CODE REVIEW

**Comment by sbragagnolo** [comment]
Issue: 
https://pharo.fogbugz.com/f/cases/edit/22531/CmdContextMenuCommandActivation-should-be-moved-to-Deprecated-package

**Comment by dionisiydk** [comment]
I think dev iceberg already fixed all these deprecations. And iceberg is
the only user of it. Do we need this true deprecation step?

пт, 26 окт. 2018 г., 16:56 Santiago Bragagnolo <notifications@github.com>:

**Comment by pavel-krivanek** [comment]
I would just delete the class

**Comment by dionisiydk** [comment]
So we just removed deprecated classes

**Pull request closed without merging**
